package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Community rules run the same guard and adapter the core linter does: each
// copy in runner/community is exactly what go generate would write now.
func TestCommunityCopiesAreCurrent(t *testing.T) {
	t.Parallel()
	want, err := copies(root)
	if err != nil {
		t.Fatal(err)
	}

	for _, m := range mirrors {
		got, err := os.ReadFile(filepath.Join(root, community, m.Name))
		if err != nil {
			t.Errorf("reading runner/community/%s, the copy of runner/lint/%s: %v; a target that runs this test must declare the copies as inputs", m.Name, m.Source, err)
			continue
		}
		if !bytes.Equal(got, want[m.Name]) {
			t.Errorf("runner/community/%s is not the current copy of runner/lint/%s; run go generate ./internal/copygen in runner/lint", m.Name, m.Source)
		}
	}
}

// A copy is marked generated, so tools skip it and people edit the source,
// is in package community, and drops the directives that would run a command
// from the wrong place or suppress nothing in a file linters skip.
func TestCopiesAreMarkedGenerated(t *testing.T) {
	t.Parallel()
	source := "// Package main.\npackage main\n\n//go:generate go run .\n//lint:ignore U1000 kept\nfunc f() {}\n"

	got, err := render("cmd/x/x.go", []byte(source))
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by go generate ./internal/copygen in runner/lint from runner/lint/cmd/x/x.go; DO NOT EDIT.\n\n// Package main.\npackage community\n\nfunc f() {}\n"
	if string(got) != want {
		t.Fatalf("copy =\n%s\nwant\n%s", got, want)
	}

	if _, err := render("cmd/x/x.go", []byte("// no package\n")); err == nil || !strings.Contains(err.Error(), "package clause") {
		t.Fatalf("a file without a package clause was copied: %v", err)
	}
}
