// Command copygen writes runner/community's copies of the core linter's
// failure guard and generated-file adapter. Community rules must fail and
// stay silent exactly as the core linter's analyzers do, but runner/community
// is a separate module that cannot import runner/lint, so it compiles copies.
// go generate ./internal/copygen in runner/lint runs this command.
package main

//go:generate go run .

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// root is runner/lint, relative to this package's directory, where both go
// generate and go test run.
var root = filepath.Join("..", "..")

// community is where the copies go, relative to runner/lint.
var community = filepath.Join("..", "community")

// mirror is one copied file: its source, relative to runner/lint, and the
// name of its copy in runner/community.
type mirror struct {
	Source string
	Name   string
}

var mirrors = []mirror{
	{Source: "policy/generated.go", Name: "generated.go"},
	{Source: "cmd/levenshtein-lint/guard.go", Name: "guard.go"},
	{Source: "cmd/levenshtein-lint/guard_test.go", Name: "guard_test.go"},
}

func main() {
	if err := write(root); err != nil {
		fmt.Fprintln(os.Stderr, "copygen:", err)
		os.Exit(1)
	}
}

// copies returns every copy's content by name, from the sources under root.
func copies(root string) (map[string][]byte, error) {
	out := map[string][]byte{}
	for _, m := range mirrors {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(m.Source)))
		if err != nil {
			return nil, err
		}
		copied, err := render(m.Source, data)
		if err != nil {
			return nil, err
		}
		out[m.Name] = copied
	}
	return out, nil
}

// render is source's copy for runner/community: marked generated, in package
// community, and without the directives that would run a command from the
// wrong place or suppress nothing in a file linters skip.
func render(source string, data []byte) ([]byte, error) {
	var text bytes.Buffer
	fmt.Fprintf(&text, "// Code generated by go generate ./internal/copygen in runner/lint from runner/lint/%s; DO NOT EDIT.\n\n", source)
	renamed := false
	for line := range strings.Lines(string(data)) {
		directive := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(directive, "//go:generate ") || strings.HasPrefix(directive, "//lint:ignore "):
		case !renamed && strings.HasPrefix(line, "package "):
			text.WriteString("package community\n")
			renamed = true
		default:
			text.WriteString(line)
		}
	}
	if !renamed {
		return nil, fmt.Errorf("runner/lint/%s has no package clause", source)
	}
	return append(bytes.TrimRight(text.Bytes(), "\n"), '\n'), nil
}

// write replaces each copy in runner/community with the current one.
func write(root string) error {
	want, err := copies(root)
	if err != nil {
		return err
	}

	for _, m := range mirrors {
		if err := os.WriteFile(filepath.Join(root, community, m.Name), want[m.Name], 0o644); err != nil {
			return err
		}
	}
	return nil
}
