package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"honnef.co/go/tools/lintcmd"
)

// unformattedMessage is LV1005's message, which the analyzer and the pass over
// excluded files share.
const unformattedMessage = "file is not gofmt-formatted; run gofmt -w"

// binaryDir holds the linter the tests build, for as long as they run.
var binaryDir string

func TestMain(m *testing.M) {
	dir, err := os.MkdirTemp("", "levenshtein-lint")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	binaryDir = dir
	status := m.Run()
	if err := os.RemoveAll(dir); err != nil {
		fmt.Fprintln(os.Stderr, err)
	}
	os.Exit(status)
}

// linterBinary builds levenshtein-lint once for the tests that run it the way
// a consumer does, with Staticcheck's cache between runs.
var linterBinary = sync.OnceValues(func() (string, error) {
	binary := filepath.Join(binaryDir, "levenshtein-lint")
	output, err := exec.CommandContext(context.Background(), "go", "build", "-o", binary, ".").CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("building the linter: %w: %s", err, output)
	}
	return binary, nil
})

// lintRun is one run of the built linter.
type lintRun struct {
	status int
	stdout string
	stderr string
}

// lintModule runs the built linter in dir over ./... with a Staticcheck cache
// that outlives the run.
func lintModule(t *testing.T, dir, cache string, args ...string) lintRun {
	t.Helper()
	binary, err := linterBinary()
	if err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	command := exec.CommandContext(t.Context(), binary, append(args, "./...")...)
	command.Dir = dir
	command.Env = append(os.Environ(), "STATICCHECK_CACHE="+cache, "GOWORK=off", "GOFLAGS=-buildvcs=false")
	command.Stdout = &stdout
	command.Stderr = &stderr
	err = command.Run()
	status := 0
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		status = exit.ExitCode()
	} else if err != nil {
		t.Fatal(err)
	}
	return lintRun{
		status: status,
		stdout: stdout.String(),
		stderr: stderr.String(),
	}
}

// writeModule writes a module of files into a new directory.
func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	// Staticcheck reports absolute paths with symlinks resolved, as go list does.
	dir, err := filepath.EvalSymlinks(dir)
	if err != nil {
		t.Fatal(err)
	}
	files["go.mod"] = "module example.com/excluded\n\ngo 1.27.1\n"
	for name, source := range files {
		writeFile(t, filepath.Join(dir, name), source)
	}
	return dir
}

func writeFile(t *testing.T, name, source string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(name, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
}

// jsonLine is the line lintcmd's JSON formatter prints for an LV1005 finding
// in file.
func jsonLine(file, severity string) string {
	return fmt.Sprintf(`{"code":"LV1005","severity":%q,"location":{"file":%q,"line":1,"column":1},"end":{"file":"","line":0,"column":0},"message":%q}`, severity, file, unformattedMessage) + "\n"
}

// Excluded files are checked after Staticcheck's run, as gofmt -l would check
// them: another platform's file and a file behind a build tag are reported,
// in every package, and generated and formatted ones are not.
func TestExcludedFilesAreReported(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"app.go":                   "package app\n",
		"integration.go":           "//go:build integration\n\npackage app\nvar  y = 1\n",
		"integration_test.go":      "//go:build integration\n\npackage app\nvar  w = 1\n",
		"formatted_ignored.go":     "//go:build ignore\n\npackage app\n",
		"generated_ignored.go":     "// Code generated by fixture. DO NOT EDIT.\n\n//go:build ignore\n\npackage app\nvar  g = 1\n",
		"nested/nested.go":         "package nested\n",
		"nested/nested_windows.go": "package nested\nvar  z = 1\n",
	})
	cache := t.TempDir()

	jsonRun := lintModule(t, dir, cache, "-f=json", "-checks=LV1005")
	textRun := lintModule(t, dir, cache, "-checks=LV1005")

	wantJSON := jsonLine(filepath.Join(dir, "integration.go"), "error") +
		jsonLine(filepath.Join(dir, "integration_test.go"), "error") +
		jsonLine(filepath.Join(dir, "nested", "nested_windows.go"), "error")
	if jsonRun.status != 1 || jsonRun.stdout != wantJSON || jsonRun.stderr != "" {
		t.Errorf("-f=json exited %d with\n%s\nstderr %q, want 1 with\n%s", jsonRun.status, jsonRun.stdout, jsonRun.stderr, wantJSON)
	}
	wantText := "integration.go:1:1: " + unformattedMessage + " (LV1005)\n" +
		"integration_test.go:1:1: " + unformattedMessage + " (LV1005)\n" +
		filepath.Join("nested", "nested_windows.go") + ":1:1: " + unformattedMessage + " (LV1005)\n"
	if textRun.status != 1 || textRun.stdout != wantText || textRun.stderr != "" {
		t.Errorf("-f=text exited %d with\n%s\nstderr %q, want 1 with\n%s", textRun.status, textRun.stdout, textRun.stderr, wantText)
	}
}

// A finding in an excluded file reads exactly as Staticcheck prints the same
// finding when the build compiles the file, so the runners that parse the
// output cannot tell them apart. The tag that compiles the file also keeps it
// from being checked twice.
func TestExcludedFindingsMatchCompiledOnes(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"app.go":         "package app\n",
		"integration.go": "//go:build integration\n\npackage app\nvar  y = 1\n",
	})
	cache := t.TempDir()

	for _, format := range []string{"-f=json", "-f=text"} {
		excluded := lintModule(t, dir, cache, format, "-checks=LV1005")
		compiled := lintModule(t, dir, cache, format, "-checks=LV1005", "-tags=integration")

		if excluded.stdout == "" || excluded.stdout != compiled.stdout || excluded.status != compiled.status {
			t.Errorf("%s: the excluded file gave %d with\n%s\nand the compiled file %d with\n%s\nwant one identical finding", format, excluded.status, excluded.stdout, compiled.status, compiled.stdout)
		}
	}
}

// Staticcheck caches a package's results by the files its build compiles, and
// excluded files are checked outside that cache, so a run on the same cache
// follows every edit to one: formatting it clears the finding, and breaking it
// again brings the finding back.
func TestExcludedFindingsFollowEditsOnACachedRun(t *testing.T) {
	unformatted := "//go:build integration\n\npackage app\nvar  y = 1\n"
	formatted := "//go:build integration\n\npackage app\n\nvar y = 1\n"
	dir := writeModule(t, map[string]string{
		"app.go":         "package app\n",
		"integration.go": unformatted,
	})
	cache := t.TempDir()

	for i, step := range []struct {
		source string
		want   int
	}{
		{unformatted, 1},
		{formatted, 0},
		{unformatted, 1},
	} {
		writeFile(t, filepath.Join(dir, "integration.go"), step.source)

		got := lintModule(t, dir, cache, "-f=json", "-checks=LV1005")

		reported := strings.Contains(got.stdout, "integration.go")
		if got.status != step.want || reported != (step.want == 1) || got.stderr != "" {
			t.Errorf("run %d exited %d with %q and stderr %q, want %d", i+1, got.status, got.stdout, got.stderr, step.want)
		}
	}
}

// The pass over excluded files follows the run's options: a selection without
// LV1005 skips it, -fail without LV1005 prints a warning that does not fail
// the run, and an output format it cannot write into leaves it out.
func TestExcludedFilesFollowTheRunOptions(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"app.go":         "package app\n",
		"integration.go": "//go:build integration\n\npackage app\nvar  y = 1\n",
	})
	cache := t.TempDir()

	for _, test := range []struct {
		args   []string
		status int
		stdout string
	}{
		{[]string{"-f=json", "-checks=SA4006"}, 0, ""},
		{[]string{"-f=json", "-checks=LV1005", "-fail=SA1000"}, 0, jsonLine(filepath.Join(dir, "integration.go"), "warning")},
		{[]string{"-f=null", "-checks=LV1005"}, 0, ""},
		{[]string{"-f=stylish", "-checks=LV1005"}, 0, " ✖ 0 problems (0 errors, 0 warnings, 0 ignored)\n"},
	} {
		got := lintModule(t, dir, cache, test.args...)

		if got.status != test.status || got.stdout != test.stdout || got.stderr != "" {
			t.Errorf("%v exited %d with %q and stderr %q, want %d with %q", test.args, got.status, got.stdout, got.stderr, test.status, test.stdout)
		}
	}
}

// Without -checks, each directory's staticcheck.conf decides whether LV1005
// checks its excluded files, as it does for the package there.
func TestExcludedFilesFollowStaticcheckConf(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"staticcheck.conf":         "checks = [\"LV1005\"]\n",
		"app.go":                   "package app\n",
		"integration.go":           "//go:build integration\n\npackage app\nvar  y = 1\n",
		"nested/staticcheck.conf":  "checks = [\"inherit\", \"-LV1005\"]\n",
		"nested/nested.go":         "package nested\n",
		"nested/nested_windows.go": "package nested\nvar  z = 1\n",
	})

	got := lintModule(t, dir, t.TempDir(), "-f=json")

	want := jsonLine(filepath.Join(dir, "integration.go"), "error")
	if got.status != 1 || got.stdout != want || got.stderr != "" {
		t.Errorf("exited %d with\n%s\nstderr %q, want 1 with\n%s", got.status, got.stdout, got.stderr, want)
	}
}

// When go list cannot list the excluded files, the run is a tool error unless
// Staticcheck's own run already failed.
func TestExcludedListingFailureIsAToolError(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "go.mod"), "not a go.mod\n")
	t.Chdir(dir)

	for _, test := range []struct {
		status int
		want   int
	}{
		{0, 2},
		{1, 1},
	} {
		command := lintcmd.NewCommand("levenshtein-lint")
		command.ParseFlags([]string{"-f=json", "-checks=LV1005", "./..."})
		var stdout, stderr bytes.Buffer

		got := checkExcluded(command.FlagSet(), []string{"LV1005"}, test.status, &stdout, &stderr)

		if got != test.want || stdout.Len() != 0 || stderr.Len() == 0 {
			t.Errorf("after status %d, exited %d with stdout %q and stderr %q, want %d with an error on stderr", test.status, got, stdout.String(), stderr.String(), test.want)
		}
	}
}
