// Code generated by go generate ./internal/checktool from internal/checktool/gitleaks.go; DO NOT EDIT.

package checktool

import (
	"encoding/json"
	"fmt"
	"strings"
)

// SecretsLeakExit is the exit code the secrets check asks gitleaks to use for
// leaks. gitleaks' own default, 1, is also what it exits with on a fatal
// error, and Go exits 2 on a panic, so neither could tell leaks from a failed
// scan.
const SecretsLeakExit = 3

// Configuration files gitleaks reads at the root of the directory it scans.
const (
	SecretsConfig = ".gitleaks.toml"
	secretsIgnore = ".gitleaksignore"
)

// SecretsArguments scans the working directory as plain files: an exported
// source has no .git, so history is out of scope on both executors. Every
// secret is fully redacted before gitleaks writes its report or a log line,
// so no secret value can reach the check's report, output, or cache. The
// report goes to a file outside the scanned directory. gitleaks reads
// .gitleaksignore from the directory it scans; a root .gitleaks.toml is named
// explicitly, and without one gitleaks uses its default rules.
func SecretsArguments(binary string, configured bool, report string) []string {
	args := []string{binary, "dir", ".", "--no-banner", "--no-color", "--redact=100", "--log-level=warn", fmt.Sprintf("--exit-code=%d", SecretsLeakExit), "--report-format=json", "--report-path=" + report}
	if configured {
		args = append(args, "--config="+SecretsConfig)
	}
	return args
}

// secretsLeak is the part of one gitleaks JSON finding the check keeps. The
// Secret, Match and Line fields are deliberately absent: they are redacted,
// but the check never reads them. Fingerprint is file:rule:line, the entry
// .gitleaksignore takes. The tags are gitleaks' field names.
type secretsLeak struct {
	RuleID      string `json:"RuleID"`
	Description string `json:"Description"`
	File        string `json:"File"`
	StartLine   int    `json:"StartLine"`
	StartColumn int    `json:"StartColumn"`
	Fingerprint string `json:"Fingerprint"`
}

// SecretsFindings turns one gitleaks run and the report it wrote into
// findings, one per leak, coded by the rule that matched. Only SecretsLeakExit
// means leaks; 0 means none, and every other exit, a missing or unreadable
// report, or a report that contradicts the exit code is an error, never a
// pass.
func SecretsFindings(run Run, report []byte) ([]Finding, error) {
	stderr := strings.TrimSpace(run.Stderr)
	if run.ExitCode != 0 && run.ExitCode != SecretsLeakExit {
		return nil, fmt.Errorf("gitleaks exited %d: %s", run.ExitCode, stderr)
	}

	var leaks []secretsLeak
	if err := json.Unmarshal(report, &leaks); err != nil {
		return nil, fmt.Errorf("gitleaks exited %d without a readable report: %w: %s", run.ExitCode, err, stderr)
	}
	if (run.ExitCode == 0) != (len(leaks) == 0) {
		return nil, fmt.Errorf("gitleaks exit %d does not match its %d findings: %s", run.ExitCode, len(leaks), stderr)
	}

	findings := make([]Finding, 0, len(leaks))
	for _, leak := range leaks {
		if leak.RuleID == "" || leak.File == "" || leak.StartLine < 1 {
			return nil, fmt.Errorf("unexpected gitleaks finding for rule %q in %q", leak.RuleID, leak.File)
		}
		findings = append(findings, Finding{
			Code:     leak.RuleID,
			Message:  fmt.Sprintf("%s The value is redacted; if it is not a secret, add %s to %s.", strings.TrimSpace(leak.Description), leak.Fingerprint, secretsIgnore),
			Location: Location{File: relative("", leak.File), Line: leak.StartLine, Column: leak.StartColumn},
		})
	}
	return findings, nil
}
