// Code generated by go generate ./internal/checktool from internal/checktool/gocheck.go; DO NOT EDIT.

package checktool

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

// gocheckOutput is levenshtein-gocheck's report: findings in the shape every
// check reports, and notes a person should see either way.
type gocheckOutput struct {
	Findings []Finding `json:"findings"`
	Notes    []string  `json:"notes"`
}

// GocheckReport reads one levenshtein-gocheck run for a check, refusing any
// result that does not agree with itself: exit 0 must carry no findings and
// exit 1 some, every one of the check's own code at a real location, with
// nothing on stderr. Exit 2, the command's own error, and any other exit are
// tool errors, never a pass. Its tests load
// runner/testdata/gocheck-reports.json.
func GocheckReport(kind Kind, run Run) ([]Finding, []string, error) {
	if run.ExitCode != 0 && run.ExitCode != 1 {
		return nil, nil, fmt.Errorf("%s could not run: %s", kind, strings.TrimSpace(run.Stderr+"\n"+run.Stdout))
	}
	var report gocheckOutput
	decoder := json.NewDecoder(strings.NewReader(run.Stdout))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&report); err != nil {
		return nil, nil, fmt.Errorf("%s printed an unreadable report: %w: %s", kind, err, output(run))
	}
	if err := decoder.Decode(new(any)); !errors.Is(err, io.EOF) {
		return nil, nil, fmt.Errorf("%s printed trailing data after its report: %s", kind, output(run))
	}
	if (run.ExitCode == 0) != (len(report.Findings) == 0) {
		return nil, nil, fmt.Errorf("%s exit %d does not match its %d findings: %s", kind, run.ExitCode, len(report.Findings), run.Stdout)
	}
	for _, found := range report.Findings {
		if found.Code != string(kind) || found.Message == "" || found.Location.File == "" || found.Location.Line < 1 {
			return nil, nil, fmt.Errorf("%s reported an unexpected finding: %+v", kind, found)
		}
	}
	if strings.TrimSpace(run.Stderr) != "" {
		return nil, nil, fmt.Errorf("%s could not produce a clean result: %s", kind, run.Stderr)
	}
	return report.Findings, report.Notes, nil
}
