// Code generated by go generate ./internal/checktool from internal/checktool/osvscanner.go; DO NOT EDIT.

package checktool

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// DepsConfig is the osv-scanner configuration deps-vuln honors at the root.
const DepsConfig = "osv-scanner.toml"

// osv-scanner's documented exit codes: 1 for vulnerabilities found, 128 for
// no packages found. Everything else nonzero is an error.
const (
	DepsVulnerableExit = 1
	depsNoPackagesExit = 128
)

// DepsTree is how the directory osv-scanner scans was prepared.
type DepsTree string

const (
	// DepsSource is the source as the target imports it, SourceSkipDirs
	// included, so the scan itself excludes them.
	DepsSource DepsTree = "source"
	// DepsStaged is a copy that already leaves SourceSkipDirs out. The scan
	// passes no exclusion: osv-scanner matches it against absolute paths, and
	// a temporary directory under, say, a vendor directory would exclude
	// every lockfile.
	DepsStaged DepsTree = "staged"
)

// DepsArguments scans every lockfile under the working directory, including
// ones .gitignore names, since the target's inputs and excludes already decide
// what is in scope. Go modules are left to go-vuln, whose govulncheck reports
// only vulnerabilities the code can reach: the go/gomod extractor is disabled,
// and call analysis, which would run govulncheck or a Rust build, is off for
// every language. The directory preset is disabled too: it would identify
// vendored C/C++ code by hashing it through the OSV API, and walk git history.
// --no-resolve keeps a manifest to the versions it names rather than resolving
// transitive dependencies through deps.dev. A root osv-scanner.toml is named
// explicitly and applies to every lockfile; without one, osv-scanner reads the
// osv-scanner.toml beside each lockfile, if there is one.
func DepsArguments(binary string, configured bool, report string, tree DepsTree) []string {
	args := []string{binary, "scan", "source", "--recursive", "--no-ignore"}
	if tree == DepsSource {
		args = append(args, "--experimental-exclude=r:(^|/)("+strings.Join(SourceSkipDirs, "|")+")(/|$)")
	}
	args = append(args, "--no-resolve", "--no-call-analysis=all", "--experimental-disable-plugins=go/gomod", "--experimental-disable-plugins=directory", "--format=json", "--output-file="+report, "--verbosity=warn")
	if configured {
		args = append(args, "--config="+DepsConfig)
	}
	return append(args, ".")
}

// depsReport is the part of osv-scanner's JSON output deps-vuln reads. The tags
// are osv-scanner's field names.
type depsReport struct {
	Results []depsResult `json:"results"`
}

type depsResult struct {
	Source   depsSource    `json:"source"`
	Packages []depsPackage `json:"packages"`
}

type depsSource struct {
	Path string `json:"path"`
}

type depsPackage struct {
	Package         depsPackageInfo `json:"package"`
	Groups          []depsGroup     `json:"groups"`
	Vulnerabilities []depsAdvisory  `json:"vulnerabilities"`
}

type depsPackageInfo struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	Ecosystem string `json:"ecosystem"`
}

// depsGroup is one set of advisories osv-scanner considers the same
// vulnerability, such as a GHSA and the CVE it aliases.
type depsGroup struct {
	IDs         []string                `json:"ids"`
	Aliases     []string                `json:"aliases"`
	MaxSeverity string                  `json:"max_severity"`
	Analysis    map[string]depsAnalysis `json:"experimental_analysis"`
}

// depsAnalysis is what osv-scanner concluded about one advisory in a group:
// whether the code calls the vulnerable function, and whether the
// distribution rates the advisory unimportant, as Debian does.
type depsAnalysis struct {
	Called      bool `json:"called"`
	Unimportant bool `json:"unimportant"`
}

// counts reports whether osv-scanner counts a group toward its exit code: a
// group is left out when no advisory in it is called or any is unimportant.
// osv-scanner still lists such a group, so deps-vuln leaves it out too, or it
// would report what osv-scanner judged needs no action and contradict its
// exit code.
func (g depsGroup) counts() bool {
	if len(g.Analysis) == 0 {
		return true
	}
	called := false
	for _, analysis := range g.Analysis {
		if analysis.Unimportant {
			return false
		}
		called = called || analysis.Called
	}
	return called
}

type depsAdvisory struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

// DepsFindings turns one osv-scanner run and the report it wrote into
// findings, one per vulnerable package version, located at the lockfile that
// pins it and naming every advisory osv-scanner counts (see depsGroups).
// osv-scanner exits 0 with nothing to report and 1 with vulnerabilities. 128
// means it found no supported lockfile, which is an error rather than an empty
// pass, as a Go check without packages is; so is any other exit, including a
// failed advisory query, a missing or unreadable report, and a report that
// contradicts the exit code. root is the scanned directory, which lockfile
// paths are reported relative to.
func DepsFindings(root string, run Run, report []byte) ([]Finding, error) {
	stderr := strings.TrimSpace(run.Stderr)
	switch run.ExitCode {
	case 0, DepsVulnerableExit:
	case depsNoPackagesExit:
		return nil, fmt.Errorf("deps-vuln found no supported dependency lockfile to scan; Go modules are go-vuln's: %s", stderr)
	default:
		return nil, fmt.Errorf("osv-scanner exited %d: %s", run.ExitCode, stderr)
	}

	var parsed depsReport
	if err := json.Unmarshal(report, &parsed); err != nil {
		return nil, fmt.Errorf("osv-scanner exited %d without a readable report: %w: %s", run.ExitCode, err, stderr)
	}

	var findings []Finding
	for _, result := range parsed.Results {
		file := strings.TrimPrefix(relative(root, result.Source.Path), "./")
		for _, pkg := range result.Packages {
			groups := depsGroups(pkg)
			if len(groups) == 0 {
				continue
			}
			if file == "" || pkg.Package.Name == "" {
				return nil, fmt.Errorf("unexpected osv-scanner result for %q in %q", pkg.Package.Name, result.Source.Path)
			}
			findings = append(findings, Finding{
				Code:     string(KindDepsVuln),
				Message:  depsMessage(pkg, groups),
				Location: Location{File: file, Line: 1},
			})
		}
	}
	if (run.ExitCode == 0) != (len(findings) == 0) {
		return nil, fmt.Errorf("osv-scanner exit %d does not match its %d vulnerable packages: %s", run.ExitCode, len(findings), stderr)
	}
	return findings, nil
}

// depsGroups are the groups of a package's advisories that osv-scanner counts
// toward its exit code, or, for a report without groups, one group per
// advisory.
func depsGroups(pkg depsPackage) []depsGroup {
	if len(pkg.Vulnerabilities) == 0 {
		return nil
	}
	if len(pkg.Groups) == 0 {
		groups := make([]depsGroup, 0, len(pkg.Vulnerabilities))
		for _, advisory := range pkg.Vulnerabilities {
			groups = append(groups, depsGroup{IDs: []string{advisory.ID}})
		}
		return groups
	}
	return slices.DeleteFunc(slices.Clone(pkg.Groups), func(group depsGroup) bool { return !group.counts() })
}

// depsMessage names the package version and, per vulnerability, its advisory
// IDs, the other IDs it is known by, its highest severity score, and its
// summary. The IDs are what an osv-scanner.toml [[IgnoredVulns]] entry takes.
func depsMessage(pkg depsPackage, groups []depsGroup) string {
	summaries := map[string]string{}
	for _, advisory := range pkg.Vulnerabilities {
		summaries[advisory.ID] = strings.TrimSpace(advisory.Summary)
	}

	parts := make([]string, 0, len(groups))
	for _, group := range groups {
		var details []string
		for _, alias := range group.Aliases {
			if !slices.Contains(group.IDs, alias) {
				details = append(details, alias)
			}
		}
		if group.MaxSeverity != "" {
			details = append(details, "severity "+group.MaxSeverity)
		}

		part := strings.Join(group.IDs, ", ")
		if len(details) > 0 {
			part = fmt.Sprintf("%s (%s)", part, strings.Join(details, ", "))
		}
		if i := slices.IndexFunc(group.IDs, func(id string) bool { return summaries[id] != "" }); i >= 0 {
			part = fmt.Sprintf("%s %s", part, summaries[group.IDs[i]])
		}
		parts = append(parts, part)
	}
	return fmt.Sprintf("%s@%s (%s) has known vulnerabilities: %s", pkg.Package.Name, pkg.Package.Version, pkg.Package.Ecosystem, strings.Join(parts, "; "))
}
