// Code generated by go generate ./internal/checktool from internal/checktool/releases.go; DO NOT EDIT.

package checktool

import (
	"fmt"
	"path"
	"strings"
)

// ReleasePin is one upstream release a shared check runs on either executor,
// as runner/toolchain.json pins it: where upstream publishes it, its version,
// and per GOOS/GOARCH platform the asset and its reviewed SHA-256. Binary is
// the binary's path inside a .tar.gz asset; an asset without it is the binary
// itself.
type ReleasePin struct {
	Releases string                  `json:"releases"`
	Version  string                  `json:"version"`
	Binary   string                  `json:"binary"`
	Assets   map[string]ReleaseAsset `json:"assets"`
}

type ReleaseAsset struct {
	Name   string `json:"name"`
	SHA256 string `json:"sha256"`
}

// Check refuses a pin that names no release or a binary outside its archive.
func (p ReleasePin) Check(tool string) error {
	if p.Releases == "" || p.Version == "" || len(p.Assets) == 0 {
		return fmt.Errorf("runner/toolchain.json pins no %s release", tool)
	}
	if p.Binary != "" && (path.Clean(p.Binary) != p.Binary || path.IsAbs(p.Binary) || p.Binary == ".." || strings.HasPrefix(p.Binary, "../") || strings.Contains(p.Binary, "\\")) {
		return fmt.Errorf("runner/toolchain.json %s binary %q is not a path inside its archive", tool, p.Binary)
	}
	return nil
}

// Asset is the pinned asset for one platform, ignoring any CPU variant a
// Dagger engine reports, such as linux/arm64/v8. A platform upstream does not
// publish, or one the pin has not reviewed, is an error rather than a fallback
// to an unverified build.
func (p ReleasePin) Asset(tool, platform string) (ReleaseAsset, error) {
	if parts := strings.Split(platform, "/"); len(parts) > 2 {
		platform = parts[0] + "/" + parts[1]
	}
	if err := p.Check(tool); err != nil {
		return ReleaseAsset{}, err
	}

	asset, ok := p.Assets[platform]
	if !ok || asset.Name == "" || strings.ContainsAny(asset.Name, `/\`) || asset.Name == ".." || len(asset.SHA256) != 64 {
		return ReleaseAsset{}, fmt.Errorf("no reviewed %s %s release asset for %s", tool, p.Version, platform)
	}
	if p.Binary != "" && !strings.HasSuffix(asset.Name, ".tar.gz") {
		return ReleaseAsset{}, fmt.Errorf("%s %s asset %s must be a .tar.gz archive", tool, p.Version, asset.Name)
	}
	return asset, nil
}

// AssetURL is where upstream publishes asset. releases replaces the pin's own
// download location when it is not empty, for tests.
func (p ReleasePin) AssetURL(asset ReleaseAsset, releases string) string {
	if releases == "" {
		releases = p.Releases
	}
	return fmt.Sprintf("%s/v%s/%s", strings.TrimSuffix(releases, "/"), p.Version, asset.Name)
}
