// Code generated by fixture. DO NOT EDIT.

package cgoparams

import "C"

func triple(value int, label string) int {
	return 3 * value
}

// Triple calls triple so it is not dead code.
func Triple(value int, label string) int {
	return triple(value, label)
}
