// Code generated by a module SDK. DO NOT EDIT.

package good

import "encoding/json"

// MarshalJSON has the value receiver Dagger's codegen gives a module's main object.
func (m Module) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}
