package policy

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"sync"

	"golang.org/x/tools/go/analysis"
)

// Community rules skip generated files exactly as the core linter's analyzers
// do, so runner/community/generated.go is generated from this file (run go
// generate ./internal/copygen in runner/lint after changing it), and
// runner/community's adapt_test.go runs that copy on this package's fixtures.

// adapt makes an analyzer report the way the shared rules do.
//
// Staticcheck's runner keys a diagnostic by its category and drops the ones
// whose category is not a registered check, so an analyzer that categorizes its
// own findings (nilness, perfsprint) would report nothing. Clearing the category
// restores the analyzer's name as the reported code. Generated files stay silent
// because nobody edits them, while the analyzer still runs there so the facts it
// exports for hand-written callers remain correct. A file is judged by its
// source, so findings in cgo's rewrite of a hand-written file still report.
func adapt(analyzer *analysis.Analyzer) {
	run := analyzer.Run
	analyzer.Run = func(pass *analysis.Pass) (any, error) {
		generated := generatedFiles(pass)
		report := pass.Report

		adapted := *pass
		adapted.Report = func(diagnostic analysis.Diagnostic) {
			if generated[pass.Fset.File(diagnostic.Pos)] {
				return
			}
			diagnostic.Category = ""
			report(diagnostic)
		}
		return run(&adapted)
	}
}

func generatedFiles(pass *analysis.Pass) map[*token.File]bool {
	generated := map[*token.File]bool{}
	for _, file := range pass.Files {
		if isGenerated(pass.Fset, file) {
			generated[pass.Fset.File(file.FileStart)] = true
		}
	}
	return generated
}

// cgoHeader opens cgo's rewrite of a hand-written file, and the next comment
// is the //line directive cgo writes to map the rest back to the original.
const cgoHeader = "// Code generated by cmd/cgo; DO NOT EDIT."

// originals remembers whether each cgo original is generated, since every
// analyzer asks for every file of a package.
var originals sync.Map

// cgoOriginal returns the original that cgo rewrote into file, if it did. The
// rewrite carries the build cache's extension-less name, which no file in a
// package directory can, so a hand-written file that copies cgo's header
// cannot send the linter to read or report on a file of its choosing.
func cgoOriginal(fset *token.FileSet, file *ast.File) (string, bool) {
	comments := file.Comments
	if filepath.Ext(fset.File(file.FileStart).Name()) != "" || len(comments) < 2 || len(comments[0].List) != 1 || comments[0].List[0].Text != cgoHeader {
		return "", false
	}

	// cgo always writes the directive as path:1:1.
	directive, ok := strings.CutPrefix(comments[1].List[0].Text, "//line ")
	if !ok {
		return "", false
	}
	original, ok := strings.CutSuffix(directive, ":1:1")
	if !ok || filepath.Ext(original) != ".go" {
		return "", false
	}
	return original, true
}

// isGenerated reports whether nobody edits the source of a parsed file. cgo
// marks its rewrite of a hand-written file as generated, so a rewritten file
// is judged by the header of the original it maps to. cgo's own additions,
// such as _cgo_gotypes.go and the header-less _cgo_import.go, carry the build
// cache's extension-less names, or a _cgo_ prefix, which the go command never
// compiles from a package directory.
func isGenerated(fset *token.FileSet, file *ast.File) bool {
	original, ok := cgoOriginal(fset, file)
	if !ok {
		name := fset.File(file.FileStart).Name()
		return ast.IsGenerated(file) || filepath.Ext(name) != ".go" || strings.HasPrefix(filepath.Base(name), "_cgo_")
	}

	if generated, ok := originals.Load(original); ok {
		return generated.(bool)
	}
	header, err := parser.ParseFile(token.NewFileSet(), original, nil, parser.PackageClauseOnly|parser.ParseComments)
	// An original that cannot be read, such as one a -trimpath build names
	// relative to its module, leaves the rewrite's own header in charge.
	generated := err != nil || ast.IsGenerated(header)
	originals.Store(original, generated)
	return generated
}
