package policy

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/analysistest"
)

func TestTypedValues(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), TypedValues, "typed")
}

// testdata/module is a module that imports a type with constants from another
// module; only the linted module's own types count as enums.
func TestTypedValuesStayInTheModule(t *testing.T) {
	analysistest.Run(t, filepath.Join(analysistest.TestData(), "module"), TypedValues, "./...")
}

func TestRecords(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Records, "records", "consumer")
}

func TestFields(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Fields, "fields")
}

func TestSpacing(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Spacing, "spacing")
}

func TestFormatting(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Formatting, "formatting")
}

// A driver that predates Pass.ReadFile leaves it nil; LV1005 then reads the
// file itself rather than failing.
func TestFormattingReadsTheFileWithoutPassReadFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "messy.go")
	if err := os.WriteFile(path, []byte("package messy\nvar  x = 1\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	var reported []analysis.Diagnostic
	pass := &analysis.Pass{Analyzer: Formatting, Fset: fset, Files: []*ast.File{file}, Report: func(d analysis.Diagnostic) { reported = append(reported, d) }}
	if _, err := Formatting.Run(pass); err != nil {
		t.Fatal(err)
	}
	if len(reported) != 1 {
		t.Fatalf("an unformatted file read without Pass.ReadFile gave %d diagnostics, want 1", len(reported))
	}
}

// Files the build leaves out, for another platform or behind a build tag, are
// not type-checked but are still Go files gofmt would check, so LV1005 reports
// them too. Staticcheck's runner leaves Pass.IgnoredFiles empty, so LV1005
// finds them in the package directory itself; a driver may list them instead.
func TestFormattingChecksIgnoredFiles(t *testing.T) {
	dir := t.TempDir()
	sources := map[string]string{
		"app.go":               "package app\n",
		"app_test.go":          "package app\n",
		"app_plan9.go":         "package app\nvar  z = 1\n",
		"integration.go":       "//go:build integration\n\npackage app\nvar  y = 1\n",
		"integration_test.go":  "//go:build integration\n\npackage app\nvar  w = 1\n",
		"tools.go":             "//go:build ignore\n\npackage main\nvar  x = 1\n",
		"formatted_ignored.go": "//go:build ignore\n\npackage app\n",
		"generated_ignored.go": "// Code generated by fixture. DO NOT EDIT.\n\n//go:build ignore\n\npackage app\nvar  g = 1\n",
	}
	for name, source := range sources {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	ignored := []string{"app_plan9.go", "formatted_ignored.go", "generated_ignored.go", "integration.go", "integration_test.go", "tools.go"}
	for i, name := range ignored {
		ignored[i] = filepath.Join(dir, name)
	}
	unformatted := []string{"app_plan9.go", "integration.go", "integration_test.go", "tools.go"}

	for _, test := range []struct {
		name    string
		files   []string
		ignored []string
		want    []string
	}{
		{"Staticcheck's runner", []string{"app.go"}, nil, unformatted},
		{"a driver that lists them", []string{"app.go"}, ignored, unformatted},
		// The build with tests sees the same directory; the plain build reports it.
		{"the build with tests", []string{"app.go", "app_test.go"}, nil, nil},
	} {
		fset := token.NewFileSet()
		var files []*ast.File
		for _, name := range test.files {
			file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			files = append(files, file)
		}

		// A driver that lists ignored files permits reading only the package's own.
		var read func(string) ([]byte, error)
		if test.ignored != nil {
			read = func(name string) ([]byte, error) {
				if !slices.Contains(test.ignored, name) && !slices.ContainsFunc(test.files, func(file string) bool { return filepath.Join(dir, file) == name }) {
					return nil, fmt.Errorf("%s is not a file of the package", name)
				}
				return os.ReadFile(name)
			}
		}

		var reported []string
		pass := &analysis.Pass{
			Analyzer:     Formatting,
			Fset:         fset,
			Files:        files,
			IgnoredFiles: test.ignored,
			ReadFile:     read,
			Report: func(d analysis.Diagnostic) {
				position := fset.Position(d.Pos)
				reported = append(reported, fmt.Sprintf("%s:%d", filepath.Base(position.Filename), position.Line))
			},
		}
		if _, err := Formatting.Run(pass); err != nil {
			t.Fatalf("%s: %v", test.name, err)
		}

		var want []string
		for _, name := range test.want {
			want = append(want, name+":1")
		}
		slices.Sort(reported)
		if !slices.Equal(reported, want) {
			t.Errorf("%s reported %v, want %v", test.name, reported, want)
		}
	}
}

func TestAssertions(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Assertions, "assertions")
}

// functions reports every function declaration, so Adapt's filter alone
// decides which files report.
func functions() *analysis.Analyzer {
	return &analysis.Analyzer{
		Name: "functions",
		Doc:  "report every function declaration",
		Run: func(pass *analysis.Pass) (any, error) {
			for _, file := range pass.Files {
				for _, decl := range file.Decls {
					if fn, ok := decl.(*ast.FuncDecl); ok {
						pass.Reportf(fn.Pos(), "function %s", fn.Name.Name)
					}
				}
			}
			return nil, nil
		},
	}
}

// A package that imports "C" is analyzed through cgo's rewrite of each file,
// which carries a generated header and lives in the build cache. Each file is
// judged by its original: the hand-written file reports, while the generated
// file and cgo's own additions, such as _cgo_gotypes.go, stay silent.
func TestCgoFiles(t *testing.T) {
	t.Setenv("CGO_ENABLED", "1")
	analysistest.Run(t, analysistest.TestData(), Adapt(functions())[0], "cgo")
	analysistest.Run(t, analysistest.TestData(), Fields, "cgofields")
	analysistest.Run(t, analysistest.TestData(), Formatting, "cgoformat")
}

// A //line directive outside cgo's rewrite does not change which file is
// generated: a generated copy that maps back to a hand-written Go file stays
// silent, and a hand-written file that maps to a template still reports.
func TestLineDirectives(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Adapt(functions())[0], "linedirective")
}

// Only a file with the build cache's extension-less name, cgo's exact header,
// and cgo's //line directive right after it maps to an original.
func TestSourceNameMapsOnlyCgoRewrites(t *testing.T) {
	const header = "// Code generated by cmd/cgo; DO NOT EDIT.\n\n"
	for _, tc := range []struct {
		name string
		file string
		src  string
		want string
	}{
		{"a rewrite with only cgo's two comments", "/cache/ab/abcd-d", header + "//line /src/demo.go:1:1\npackage demo\n", "/src/demo.go"},
		{"a rewrite with more comments after them", "/cache/ab/abcd-d", header + "//line /src/demo.go:1:1\npackage demo\n\n// Later.\nvar x int\n", "/src/demo.go"},
		{"cgo's header without a directive", "/cache/ab/abcd-d", header + "package demo\n", "/cache/ab/abcd-d"},
		{"a directive cgo would not write", "/cache/ab/abcd-d", header + "//line /src/demo.go:7:1\npackage demo\n", "/cache/ab/abcd-d"},
		{"an original that is not Go", "/cache/ab/abcd-d", header + "//line /src/demo.tmpl:1:1\npackage demo\n", "/cache/ab/abcd-d"},
		{"a package file that copies cgo's header", "/src/copy.go", header + "//line /src/demo.go:1:1\npackage demo\n", "/src/copy.go"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, tc.file, tc.src, parser.ParseComments|parser.SkipObjectResolution)
			if err != nil {
				t.Fatal(err)
			}

			if got := SourceName(fset, file); got != tc.want {
				t.Errorf("SourceName = %q, want %q", got, tc.want)
			}
		})
	}
}
