package policy

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"sync"
)

// cgoHeader opens cgo's rewrite of a hand-written file, and the next comment
// is the //line directive cgo writes to map the rest back to the original.
const cgoHeader = "// Code generated by cmd/cgo; DO NOT EDIT."

// originals remembers whether each cgo original is generated, since every
// analyzer asks for every file of a package.
var originals sync.Map

// SourceName names the file a developer edits for one parsed file of a
// package. For a package that imports "C", the analyzers see cgo's rewrite of
// each hand-written file, which lives in the build cache and names the
// original in the //line directive under its generated header; that original
// is the source. Every other file is its own source, whatever its own //line
// directives say, so a generated copy of a Go file or a goyacc parser is
// judged as it always was.
func SourceName(fset *token.FileSet, file *ast.File) string {
	if original, ok := cgoOriginal(fset, file); ok {
		return original
	}
	return fset.File(file.FileStart).Name()
}

// cgoOriginal returns the original that cgo rewrote into file, if it did. The
// rewrite carries the build cache's extension-less name, which no file in a
// package directory can, so a hand-written file that copies cgo's header
// cannot send the linter to read or report on a file of its choosing.
func cgoOriginal(fset *token.FileSet, file *ast.File) (string, bool) {
	comments := file.Comments
	if filepath.Ext(fset.File(file.FileStart).Name()) != "" || len(comments) < 2 || len(comments[0].List) != 1 || comments[0].List[0].Text != cgoHeader {
		return "", false
	}

	// cgo always writes the directive as path:1:1.
	directive, ok := strings.CutPrefix(comments[1].List[0].Text, "//line ")
	if !ok {
		return "", false
	}
	original, ok := strings.CutSuffix(directive, ":1:1")
	if !ok || filepath.Ext(original) != ".go" {
		return "", false
	}
	return original, true
}

// Generated reports whether nobody edits the source of a parsed file. cgo
// marks its rewrite of a hand-written file as generated, so a rewritten file
// is judged by the header of the original it maps to. cgo's own additions,
// such as _cgo_gotypes.go and the header-less _cgo_import.go, carry the build
// cache's extension-less names, or a _cgo_ prefix, which the go command never
// compiles from a package directory.
func Generated(fset *token.FileSet, file *ast.File) bool {
	original, ok := cgoOriginal(fset, file)
	if !ok {
		name := fset.File(file.FileStart).Name()
		return ast.IsGenerated(file) || filepath.Ext(name) != ".go" || strings.HasPrefix(filepath.Base(name), "_cgo_")
	}

	if generated, ok := originals.Load(original); ok {
		return generated.(bool)
	}
	header, err := parser.ParseFile(token.NewFileSet(), original, nil, parser.PackageClauseOnly|parser.ParseComments)
	// An original that cannot be read, such as one a -trimpath build names
	// relative to its module, leaves the rewrite's own header in charge.
	generated := err != nil || ast.IsGenerated(header)
	originals.Store(original, generated)
	return generated
}
