// Command copygen writes runner/internal/checktool, the Dagger runner's copy
// of internal/checktool. go generate ./internal/checktool runs it from that
// directory.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// runnerCopy is the copy's directory, relative to internal/checktool.
var runnerCopy = filepath.Join("..", "..", "runner", "internal", "checktool")

func main() {
	if err := write(".", runnerCopy); err != nil {
		fmt.Fprintln(os.Stderr, "copygen:", err)
		os.Exit(1)
	}
}

// copies returns the copy's files by name: every non-test Go file of the
// package in source, marked generated. The copy drops the go:generate
// directive, which names this command by a path the copy does not have, and
// every //lint:ignore: linters skip a generated file, so a directive there
// would suppress nothing and be reported as stale. The source keeps both.
func copies(source string) (map[string][]byte, error) {
	files, err := filepath.Glob(filepath.Join(source, "*.go"))
	if err != nil {
		return nil, err
	}

	out := map[string][]byte{}
	for _, file := range files {
		name := filepath.Base(file)
		if strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}

		var text bytes.Buffer
		fmt.Fprintf(&text, "// Code generated by go generate ./internal/checktool from internal/checktool/%s; DO NOT EDIT.\n\n", name)
		for line := range strings.Lines(string(data)) {
			directive := strings.TrimSpace(line)
			if !strings.HasPrefix(directive, "//go:generate ") && !strings.HasPrefix(directive, "//lint:ignore ") {
				text.WriteString(line)
			}
		}
		out[name] = append(bytes.TrimRight(text.Bytes(), "\n"), '\n')
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s has no Go files to copy", source)
	}
	return out, nil
}

// write replaces the Go files in dest with the copies of source's.
func write(source, dest string) error {
	want, err := copies(source)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dest, 0o755); err != nil {
		return err
	}

	stale, err := filepath.Glob(filepath.Join(dest, "*.go"))
	if err != nil {
		return err
	}
	for _, file := range stale {
		if _, ok := want[filepath.Base(file)]; !ok {
			if err := os.Remove(file); err != nil {
				return err
			}
		}
	}

	names := make([]string, 0, len(want))
	for name := range want {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		if err := os.WriteFile(filepath.Join(dest, name), want[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}
