package main

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// The runner compiles the same checktool the native executor does: its copy
// is exactly what go generate would write now, with no file missing, changed,
// or left over.
func TestRunnerCopyIsCurrent(t *testing.T) {
	want, err := copies("..")
	if err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join("..", runnerCopy)
	present, err := filepath.Glob(filepath.Join(dest, "*.go"))
	if err != nil {
		t.Fatal(err)
	}

	var names []string
	for _, file := range present {
		names = append(names, filepath.Base(file))
	}
	for name, data := range want {
		got, err := os.ReadFile(filepath.Join(dest, name))
		if err != nil || !bytes.Equal(got, data) {
			t.Errorf("runner/internal/checktool/%s is not the current copy of internal/checktool/%s; run go generate ./internal/checktool", name, name)
		}
	}
	for _, name := range names {
		if _, ok := want[name]; !ok {
			t.Errorf("runner/internal/checktool/%s has no source in internal/checktool; run go generate ./internal/checktool", name)
		}
	}
	if len(names) == 0 {
		t.Error("runner/internal/checktool is missing; run go generate ./internal/checktool")
	}
}

// A copy is marked generated, so tools skip it and people edit the source,
// and drops the directive that would run this command from the wrong place.
func TestCopiesAreMarkedGenerated(t *testing.T) {
	source := t.TempDir()
	if err := os.WriteFile(filepath.Join(source, "doc.go"), []byte("// Package p.\npackage p\n\n//go:generate go run ./copygen\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(source, "doc_test.go"), []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := copies(source)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by go generate ./internal/checktool from internal/checktool/doc.go; DO NOT EDIT.\n\n// Package p.\npackage p\n"
	if len(got) != 1 || string(got["doc.go"]) != want {
		t.Fatalf("copies = %q, want only doc.go as %q", got, want)
	}
}

// write leaves dest holding the copies and nothing else.
func TestWriteRemovesStaleFiles(t *testing.T) {
	source, dest := t.TempDir(), t.TempDir()
	if err := os.WriteFile(filepath.Join(source, "a.go"), []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dest, "gone.go"), []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := write(source, dest); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(dest)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, entry := range entries {
		names = append(names, entry.Name())
	}
	if !slices.Equal(names, []string{"a.go"}) {
		t.Fatalf("dest holds %v, want only a.go", names)
	}
	data, err := os.ReadFile(filepath.Join(dest, "a.go"))
	if err != nil || !strings.HasSuffix(string(data), "package p\n") {
		t.Fatalf("a.go = %q, %v", data, err)
	}
}
